-- 코드를 입력하세요
#SELECT BOOK_ID, PUBLISHED_ID FROM BOOK
#WHERE PUBLISHED_DATE LIKE ='2021%'
#AND CATEGORY = '인문'
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND YEAR(PUBLISHED_DATE) = '2021'
ORDER BY PUBLISHED_DATE ASC;